# Collects the built plugins, the Library app and the licence files into dist/Monomodule-<version>-<platform>-<arch>.zip.
#   cmake -DBUILD_DIR=build -DOUT_DIR=dist -DPLATFORM=macos|linux|windows -P cmake/stage_release.cmake
# The plugins must already be built (Release). Used by .github/workflows/build.yml.
foreach(v BUILD_DIR OUT_DIR PLATFORM)
  if(NOT ${v})
    message(FATAL_ERROR "stage_release: -D${v}=... is required")
  endif()
endforeach()
get_filename_component(SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
get_filename_component(OUT_DIR "${OUT_DIR}" ABSOLUTE)

file(STRINGS "${SRC_DIR}/CMakeLists.txt" _proj REGEX "^project\\(Monomodule VERSION [0-9.]+")
string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" VERSION "${_proj}")
if(PLATFORM STREQUAL "macos")
  set(ARCH universal)
else()
  cmake_host_system_information(RESULT ARCH QUERY OS_PLATFORM)
  string(TOLOWER "${ARCH}" ARCH)
  if(ARCH MATCHES "^(x86_64|amd64)$")
    set(ARCH x64)
  elseif(ARCH MATCHES "^(aarch64|arm64)$")
    set(ARCH arm64)
  endif()
endif()
set(NAME "Monomodule-${VERSION}-${PLATFORM}-${ARCH}")
set(STAGE "${OUT_DIR}/${NAME}")
file(REMOVE_RECURSE "${STAGE}")
file(MAKE_DIRECTORY "${STAGE}/VST3")

set(PLUGINS "One:MnmOne" "Six:MnmSix" "FX:MnmFx")
foreach(p ${PLUGINS})
  string(REPLACE ":" ";" p "${p}")
  list(GET p 0 short)
  list(GET p 1 target)
  set(art "${BUILD_DIR}/src/plugin/${target}_artefacts/Release")
  file(COPY "${art}/VST3/Monomodule ${short}.vst3" DESTINATION "${STAGE}/VST3")
  if(PLATFORM STREQUAL "macos")
    file(COPY "${art}/AU/Monomodule ${short}.component" DESTINATION "${STAGE}/AU")
  endif()
  if(EXISTS "${art}/Standalone")
    file(GLOB standalone "${art}/Standalone/*")
    file(COPY ${standalone} DESTINATION "${STAGE}/Standalone")
  endif()
endforeach()

set(app "${BUILD_DIR}/src/app/MnmLibraryApp_artefacts/Release")
file(GLOB app_files "${app}/Monomodule Library*")
file(COPY ${app_files} DESTINATION "${STAGE}/Library")

file(COPY "${SRC_DIR}/LICENSE" "${SRC_DIR}/THIRD_PARTY_NOTICES.md" "${SRC_DIR}/README.md" DESTINATION "${STAGE}")

execute_process(COMMAND ${CMAKE_COMMAND} -E tar cf "${NAME}.zip" --format=zip "${NAME}"
                WORKING_DIRECTORY "${OUT_DIR}" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "stage_release: zip failed")
endif()
message(STATUS "staged ${OUT_DIR}/${NAME}.zip")
